### ISSUE TITLE
Think it'll work with angular ui router?

### ISSUE THREAD

**Issue by morgs32** [DevAndyLee/Angular-Hero-Sample#1]
Gonna get to work trying - just curious if you knew already.

**Comment by andy-lee-eng** [comment]
I haven't tried it, but I'm fairly certain it'll work - my previous project (the inspiration for this one) used angular ui router, and worked in basically the same way.

**Comment by morgs32** [comment]
Hey Andy, I just created a request on airpair.com for someone to pair up with me to tackle some improvements to your plugin. I'm think of building an angular service to queue animations - such as the hero transition has to happen and *then* the ng-repeat staggers in. Also, I have to create a variation of your hero animation for when it is also a page transition - (from a hero-id on a button for instance to a hero-id on the whole view) should happen before the rest of the view fades in. I was going to pay 70/hr on airpair. Would that interest you?

**Comment by nzmedet** [comment]
Yes it works! https://github.com/vko-online/Angular-Hero-Sample
