### ISSUE TITLE
Implementing outside angular 

### ISSUE THREAD

**Issue by Pandahisham** [DevAndyLee/Angular-Hero-Sample#2]
Can you please guide how this could be implemented outside of a single page app ? I was thinking may be storing the position of the hero element in a cookie and calling it in the next page and animating then , an angular free implementation would be welcomed

**Comment by Pandahisham** [comment]
i am using jquery smoothstate

**Comment by andy-lee-eng** [comment]
I guess you'd have a fair bit of work to do without Angular's built in support for animated transitions. In particular, with whatever system you're using, you need to make sure that the new DOM and the old DOM are on the screen at the same time until the transition has finished. Assuming you've cracked that, it should be fairly straight forward to locate both elements, and transition from one to the other.
