### ISSUE TITLE
Broken on safari

### ISSUE THREAD

**Issue by honkskillet** [DevAndyLee/Angular-Hero-Sample#3]
Hi,
Cool repo.  Unfortunately it is broken on Safari.  The icons animate but they never end up in the correct spot.  Usually they just get their height distorted at their original position.

I tried this app on Max OS X Chrome and Firefox too and they seemed to work fine.

Also, readme could use some TLC.  It would be helpful to instruct users to git clone the repo.  More importantly the link to localhost 8000 in the readme is incorrect.  it uses \ when it should use /.  (Or is that a PC thing?)

**Comment by andy-lee-eng** [comment]
Thanks,

I have fixed the Safari issue in the [Angular-Hero](https://github.com/DevAndyLee/Angular-Hero) project and bower package, and updated the sample hosted in the blog post.

I've also updated the localhost link.
